services:
  epics-ioc:
    image: prjemian/synapps:R6-3
    environment:
      - EPICS_CA_ADDR_LIST=localhost
      - EPICS_CA_AUTO_ADDR_LIST=YES
    ports:
      - "5064:5064/tcp"
      - "5065:5065/tcp"
      - "5064:5064/udp"
      - "5065:5065/udp"
    volumes:
      - ./test.db:/test.db:ro
    command: softIoc -d /test.db
